### ISSUE TITLE
ADPCM support

### ISSUE THREAD

**Issue by ScoopJohn** [rerrahkr/BambooTracker#6] opened 2018-11-26 13:31 UTC
This tracker is surely promising, but i've noticed some issues:

**1.** After adding my first instrument and messing over with the parameters, i created a new one and somehow it overrides with the other instrument, it seems that the operators apply to every instrument you create at the moment.
**2.** The lack of the ADPCM channel, i'm sure this isn't really a problem but just letting myself know about that.
**3.** The volume column seems to scale volume in a reversed order. 00 being the loudest and 7F being the quietest.
**4.** Are you going to have support for loading Deflemask (.dmp) patch files?

**Comment by rerrahkr** [comment] 2018-11-26 14:11
Hi, thank you for raising issues.
I will try to fix 1 and 3. Currently ADPCM does not exist but will be added in future releases. I don't know how Deflemask works. I don't know if that can be done, but I would like to try it.

**Comment by DeltaRazero** [comment] 2018-11-26 14:58
I would like to comment that 00 being loudest and 7F being the quietest is how the hardware works, which is why it is present in many trackers and MML compilers.

For .DMP support, [this is the document with the .DMP format specification](http://www.deflemask.com/DMP_SPECS.txt). I can provide code too from my unfinished library I mentioned in [A few requests to make the usability better](https://github.com/rerrahkr/BambooTracker/issues/2).

**Comment by Xyz39808** [comment] 2018-11-27 03:42
Yes, for a lot of FM hardware (and SN76489), there is no volume register, rather, it's a volume attenuation register.
Though maybe that significance could be indicated in the instrument editor.

**Comment by jimbo1qaz** [comment] 2018-11-28 23:04
Prepend a minus sign... Though that may make the ui messy.

**Comment by SexyZombieRoo** [comment] 2018-11-30 14:17
In regards to the instruments overwriting each other: I found that deep clones don't suffer that problem, so right now I use deep cloning then modifying the clone as a workaround to that issue.

**Comment by rerrahkr** [comment] 2018-12-14 14:03
I fixed instrument editor to set new properties when adding a new instrument 67d1b8a043c11f235a9c621ca0a4c94a601c9866.

**Comment by superctr** [comment] 2019-05-08 15:06
If it's any use, I have an ADPCM codec [here](https://github.com/superctr/adpcm/blob/master/ymb_codec.c) which can be easily embedded into applications. It can be used for both conversion and playback (integration into chip emulators), if needed.

**Comment by N-SPC700** [comment] 2019-05-13 21:02
Sorry to hijack the ADPCM discussion, but would it be feasible to add SSGPCM into the mix as well? I only ask for this as sometimes the ADPCM channel alone isn't enough.

**Comment by Pigu-A** [comment] 2019-05-14 01:26
No, SSGPCM is software mixed and it's not exportable to S98 or would create a really big VGM file. Also, it can't be played at a decent sample rate for slow CPUs such as PC-88 or original MSX's Z80 CPU.

**Comment by N-SPC700** [comment] 2019-05-14 12:22
> or original MSX's Z80 CPU.
This tracker is for PC88/98 only, no?
> for slow CPUs such as PC-88
ZX Spectrum (3MHz Z80) can do three channels of 4-bit samples completely fine, so unless these machines are _a step back_ I don't see why it wouldn't be practical. I do understand the VGM thing though. Register writes are memory hungry, and bitbanging 3 SSG channels could be a pain.

**Comment by superctr** [comment] 2019-05-14 12:25
VGM has the "DAC stream" feature that can be used for things like this, essentially streaming writes to a register from a datablock. This is usually used for YM2612 DAC writes, hence the name. However, this is a bit of an advanced feature and AFAIK no real hardware replayers support this.

**Comment by Pigu-A** [comment] 2019-05-14 13:09
Ah, then I just remembered that VGM feature wrong then (there are rips that doesn't utilize it).

For ZX Spectrum doing 3 channels PCM fine, that only applies for the case of samples data being very optimized for it and there are literally nothing else running aside. Stuff like mixing and playback engine overhead would make playback at a decent sample rate in this case gets impractical very fast. I mentioned MSX because there's OPNA cart being developed for it.

**Comment by superctr** [comment] 2019-05-14 13:30
If you're going to play back on MSX and need more PCM channels, then a solution would be to use  mod2vgm or a similar tool to create the PCM track (using the Moonsound YMF278B cartridge, giving you 24 PCM channels), then use `vgmmerge` to merge the FM and PCM tracks. In that case you will still need a Moonsound cartridge and probaly a slot expander, but it would still be cheaper than using SSG PCM which will almost surely require a Turbo-R.

**Comment by N-SPC700** [comment] 2019-05-14 14:05
" I mentioned MSX because there's OPNA cart being developed for it."

That's more on you, for choosing to use inferior hardware to playback OPNA music. Besides, as said before, other games use SSGPCM, so why bother dumbing down a **PC88/98** tracker so you can run it on a MSX?

**Comment by pedipanol** [comment] 2019-05-14 14:35
As currently stands, BambooTracker is a VGM/S98-only tracker at this point. As far as I'm aware (correct me if I'm wrong), currently, the only way to play it on PC-88/98 hardware is the S98players, which the PC88 one only lets you files use up to 128kb (and doesn't support SSGPCM on VGM files that use it), and the PC98 one has problems with tracks playing slower in some machines https://twitter.com/maakmusic/status/1099936358301294593 . The second one would most likely run even slower with SSG PCM, since it's software-controlled and VGM is already unoptimized being a logged format.

I think SSG PCM should only come into discussion once BambooTracker has a proper hardware player rather than only VGM/S98

**Comment by superctr** [comment] 2019-05-14 14:43
To add, regarding this comment:
> so why bother dumbing down a PC88/98 tracker so you can run it on a MSX?

The tracker targets a specific sound chip (YM2608) right now, it was not standard equipment on either the PC88 or PC98 series and supporting it still doesn't make it dependent on any of the mentioned platforms.

The readme says `BambooTracker is a music tracker for the Yamaha YM2608 (OPNA) sound chip which was used in NEC PC-8801/9801 series computers.` So that would not make it an MSX or PC88 or even a PC98 tracker, for now it's just a YM2608 tracker.

**Comment by ImATrackMan** [comment] 2019-05-16 10:18
> " I mentioned MSX because there's OPNA cart being developed for it."
> 
> That's more on you, for choosing to use inferior hardware to playback OPNA music.
As the developer of the cart, thanks for the feedback.

Anyway, VGM is horribly inefficient and as it stands, it'd be equally impractical to implement raw data streaming. MSX plays VGMs back at 4kHz at best on a Turbo-R and 50 Hz at worst on a PAL MSX1, so that's the kicker right there.

PC-98 fares better not just because of the faster CPU, but because S98 typically only has a timing resolution of 1kHz (in this case, an MSX can potentially play a file back with 4x the resolution of a PC-98, throwing your inferior hardware quip out the window), so a PC-98 potentially has less data to push. Even then, however, it still slows down on a PC-98, so the concept of the tracker having a "target system" is more irrelevant than it already was.

In the case of it being an OPNA tracker, the 2608 having an 8-bit data bus means anything with an 8-bit bus or higher can talk to it pretty easily, meaning it can be used with practically any system. Doesn't it make more sense to make the software's output compatible with as many potential targets as possible rather than just the absolute most powerful?

**Comment by ImATrackMan** [comment] 2019-05-16 10:38
Also, before I forget, an idea on how to handle samples and repitching them if/when ADPCM is implemented.

Effect changes the sample, normal keyboard/MIDI keys change pitch as usual.

>C-6 -- 89 SM02

would play Sample 02 at 4186 Hz  at volume level $89, for example.

**Comment by Pigu-A** [comment] 2019-05-16 11:45
Why don't just use an instrument number as a sample number? You can even have it refer to the different set aside from FM/SSG like how most MML compilers do.

**Comment by superctr** [comment] 2019-05-16 13:47
The way deflemask handles samples is completely backwards and hopefully will not be considered. Mapping samples to instruments (possibly with a keysplit / note map) would be the most intuitive and match the behavior of other module formats, XM/S3M/IT etc.

**Comment by OPNA2608** [comment] 2019-05-16 17:39
> As the developer of the cart, thanks for the feedback.

I really respect your effort to expand the MSX's audio capabilities with a YM2608, despite everything I have to say. I'm sure everyone here does, despite what they might say in the heat of the discussion.

> Anyway, VGM is horribly inefficient

I don't think anyone's denying that, especially for playback on actual hardware ;)

> _MSX_ plays **VGM**s back at _4kHz at best_ [...] _and 50 Hz at worst_
> _PC-98_ fares better not just because of the faster CPU, but because **S98 typically** only has a timing resolution of _1kHz_ [...] throwing your inferior hardware quip out the window

Aren't you comparing apples and pears here? Those are 2 different logging formats, seems kind of unfair to say the least. :)

> Doesn't it make more sense to make the software's output compatible with as many potential targets as possible rather than just the absolute most powerful?

I think neither makes sense.

- If you only pander to the compatibility camp, you'll disappoint those that ***want*** the extra power utilized.
- If you try to please the power horses, someone with less capable/different hardware will curse you into infinity.

Fact is, the PC-8800 and PC-9800 are - and for years have been - the main implementation of the YM2608, so to speak, and SSGPCM was used by some games. The fact that you're working on a board to expand another system with it does not change that fact.
And as someone who recently did a PMD song heavily utilizing SSGPCM, I'd really appreciate support for it in BambooTracker.

That being said, what speaks against implementing SSGPCM (with a lower priority than proper ADPCM support, _naturellement_), but specifing that certain systems/platforms/formats might not be capable of playing it back?
You wouldn't have to use it if you don't want to, a hardware player of BambooTracker modules (if you want to spin it that far) could even just silently drop those instructions when attempting to play such a module back on insufficient hardware.

Where would the harm be in that, if I may inquire?

**Comment by superctr** [comment] 2019-05-16 18:35
If you look into it, VGM and S98 are pretty similar formats. S98 though, does not have the DAC stream feature and the default sample rate is lower, making SSGPCM impossible. VGM's dac streams can be hardware accelerated in theory but in practice it's hard (impossible for PC88 and non-Turbo R MSXes, maybe possible for PC98).

So, if you're one of those "power horses", and now that we have eliminated all other possible target platforms, why stop at SSGPCM. PC9821, and at least the later '01 models, has a Crystal CS4231 PCM codec, which could be used to do sample mixing outside the FM chip, using both less resources and has higher quality than SSGPCM. At that point, you could just have a hybrid FM+PSG tracker a la Screamtracker 3.

Alas, now we are just a YM2608 exclusive tracker.

**Comment by ImATrackMan** [comment] 2019-05-17 05:04
> Why don't just use an instrument number as a sample number? You can even have it refer to the different set aside from FM/SSG like how most MML compilers do.

Single instrument to edit and rearrange samples instead of having 7 instruments being tone/sample and X more being only samples with no other settings. Better than Deflemask's way of having a note being a different sample and only being able to control pitch purely through effects.

**Comment by superctr** [comment] 2019-05-17 06:11
Sample instruments can still support pitch and volume effects. Keep in mind that YM2608 can play samples at arbitrary sample rates.

**Comment by ImATrackMan** [comment] 2019-05-17 10:42
>Sample instruments can still support pitch and volume effects. Keep in mind that YM2608 can play samples at arbitrary sample rates.

I never implied it couldn't. My first post with this idea even gives an arbitrary 4.1 kHz rate at an arbitrary $89 volume level.

**Comment by superctr** [comment] 2019-05-17 13:41
Well, my point is simple, if we have a dedicated channel (column) for the ADPCM channels, then having to use the effect column to select samples is bad design since it completely negates the use of the instrument column.

But since you mentioned Famitracker and Deflemask (ugh...), let me point out the background behind and the flaws in their approaches too:

Famitracker actually does not confine samples to one instrument, each instrument has its own sample note map. However on Famitracker the DPCM channel share the same instrument type as regular tone/noise channels. I think this is bad design because the sample section is ignored when using an instrument on a tone/noise channel and the envelopes are ignored on the sample channel. If you are a new user, you might get surprised when you don't hear anything after you try to use the DPCM channel using a regular 2A03 instruemnt. On the other hand, expansion audio does have their own instrument type and Famitracker will not let you enter notes in an expansion audio channel until you create an instrument for that channel first.

Deflemask has a global sample list, but no sample instrument type. This is probably inherited from VGM Music Maker, which had a similar method. I believe this method really only makes sense if there is no dedicated PCM channel, the 2612 has a special relation between the PCM and FM6; you can play notes on FM6 while playing samples though the FM output is muted. Hence why you trigger samples with an effect (on any channel).

The 2610 on the other hand has hardware ADPCM playback, there is no need to share the ADPCM and FM channels.

The rhythm sound source, as you mentioned, is a special case since the samples are hard-coded to an internal ROM. The 2610's ADPCM-A works similar to the RSS, except it actually loads samples from external memory. So while it would make sense not to have sample-type instruments for the 2608, if support for the 2610 is added in the future, it would also need a unique instrument type since the ADPCM-A samples are not compatible with the ADPCM-B channel.

**Comment by pedipanol** [comment] 2019-05-18 14:00
One way I think ADPCM implementation could work is the way SuperC handles it:

When creating an ADPCM instrument, on the instrument edit screen you'd have by default the ability to select 1 sample for the instrument, but also a way to enable a "Drumkit" mode, which works similar to famitracker, assigning different samples to notes

**Comment by superctr** [comment] 2019-05-18 14:16
Yeah, that's pretty much what I'm thinking of.

**Comment by Ravancloak** [comment] 2019-08-29 19:35
I only know a little about how the PC-98 handles samples, but after making a sample bank for PMD, and knowing how Defle and Fami work, I had an idea of how to handle samples: Just import compatible sample files into a bank; and have an effects command that allows you to use samples, (17 for example) and in the value area, specify which sample to use (like 01 for sample 1), and then allow for the notes column to specify what frequency to play back the note. Even if you can't export a module that has samples; this would be nice for people like me who want to make PC-98 music for the sake of music; not accurate playback. Even having another module property (similar to the ch3 mode thing) that allows for sample features for people like me would be a great solution.

**Comment by papiezak** [comment] 2019-08-29 19:53
>and have an effects command that allows you to use samples, (17 for example) and in the value area

There is no need for that 😉 . YM2608 has a dedicated ADPCM channels that's only for sample playback and YM2608B (OPNA rev. B, used in PC-9801-86 soundcards and PC-9821 computers) has a completely separated PCM hardware (PPZ8?) 

> allow for the notes column to specify what frequency to play back the note

I'm not 100% sure if ADPCM channel allows you to have such a pitch control.

**Comment by Ravancloak** [comment] 2019-08-29 19:58
Whatev, I just really want samples (enough to learn PMD). iirc, there is a way to use the fm channels for samples; this is what I was addressing.

**Comment by superctr** [comment] 2019-08-30 05:45
> Whatev, I just really want samples (enough to learn PMD). iirc, there is a way to use the fm channels for samples; this is what I was addressing.
The ADPCM channel is completely separate from FM, you can use all 6 FM channels while playing samples on the ADPCM channel.

> YM2608 has a dedicated ADPCM channels that's only for sample playback and YM2608B (OPNA rev. B, used in PC-9801-86 soundcards and PC-9821 computers) has a completely separated PCM hardware (PPZ8?)
Not true, while it is true that later PC98 variants do have separate PCM hardware (actually it's similar hardware to later IBM PCs), the YM2608 ADPCM channel is still there in the B-variant too. However YMF288 does not have ADPCM.

**Comment by bryc** [comment] 2019-09-12 00:46
>  iirc, there is a way to use the fm channels for samples

@Ravancloak Not without very CPU-intensive custom software code (like getting samples to play on any chip). The YM2608 cannot play samples natively with the FM channels. I think you are thinking of the YM2612 which has a special DAC mode for FM CH6 for sample playback. That was meant as a replacement for the ADPCM channel (YM2612 is a cost-reduced version of YM2612).

**Comment by ImATrackMan** [comment] 2020-01-12 05:12
So, has there been any development or interest in this at all? Just asking. Seems a bit odd that a core feature of the chip is still stuck in "how do we start" hell after a year and a half.

**Comment by rerrahkr** [comment] 2020-01-12 09:27
I plan to implement ADPCM features this year. I will first test ADPCM with the MAME emulator using YM2608 Tone Editor, then decide on the instrument format discussed above and implement it in BambooTracker.
I will be busy with my work in this year, so it will take some time to complete the implementation.

I have been researching how to use ADPCM since last week. However, how to use ADPCM with the MAME emulator is not yet well understood.

**Comment by rerrahkr** [comment] 2020-02-01 12:59
I explain about my planned ADPCM feature.

> When creating an ADPCM instrument, on the instrument edit screen you'd have by default the ability to select 1 sample for the instrument, on this mode, using different notes changes the pitch of said sample. But also it would have a way to enable a "Drumkit" mode, which works similar to famitracker, assigning different samples to notes, the pitch being defined on the instrument edit screen.

I stand by @pedipanol's idea. And in a single ADPCM instrument (not drumkit instrument), I will implement envelope, arpeggio and pitch sequence like SSG instrument and selection whether to enable loop playback.

When importing sample, BambooTracker converts .wav to 4-bit mono ADPCM. Sampling rate and base tone is selectable before the conversion.

I have some plans like sample waveform shape edit by ADPCM instrument, but it will take some time, so I will release the tracker with at least ADPCM usable, and I will improve it later. v0.4.0, the first ADPCM available version, will limit the loadable sample rate 2k-16kHz, and not implement kit yet.

**Comment by Pigu-A** [comment] 2020-02-01 16:59
> Sampling rate and base tone is selectable before the conversion.

I personally wanted the sampling rate as a part of the instrument data though. Something like S3M and IT's C5 frequency.

**Comment by rerrahkr** [comment] 2020-02-02 10:13
> I personally wanted the sampling rate as a part of the instrument data though. Something like S3M and IT's C5 frequency.

I don't know much about these trackers, but I checked a little on Schism Tracker, is it about "Speed" in Sample list? It's like sample rate at base tone, which seems to be useful to edit sample's waveform shape.
I also add resampling settings when loading samples to change its size.

**Comment by papiezak** [comment] 2020-02-02 10:42
>When importing sample, BambooTracker converts .wav to 4-bit mono ADPCM

Is ADPCM playback capped to only 4-bit? I'm asking since multiple sources seem to state that channels use 8-bit format, while official YM2608 application manual, on the other hand:
>Sampling rate 2kHz-16kHz
 AD/DA conversion 8bit
 **ADPCM analysis 4bit**

**Comment by Pigu-A** [comment] 2020-02-02 10:58
> I don't know much about these trackers, but I checked a little on Schism Tracker, is it about "Speed" in Sample list?

Yes. What I implied is that the player will take both of this base frequency and the current pitch to calculate the final pitch value.

> Is ADPCM playback capped to only 4-bit? I'm asking since multiple sources seem to state that channels use 8-bit format, while official YM2608 application manual, on the other hand:
> 
> > Sampling rate 2kHz-16kHz
> > AD/DA conversion 8bit
> > **ADPCM analysis 4bit**

The playback itself is 8-bit (and even 16-bit internally). It's just that the format itself contains a 4-bit of compressed data per sample.

**Comment by superctr** [comment] 2020-02-02 11:57
Basically, a sample can be recorded at any arbitrary rate while tuned to a specific note. So you can have a sample tuned for C-5 at 16khz, or A-3 at 9.5khz etc. When playing back, the sample should be transposed so it will be stay in tune.

**Comment by papiezak** [comment] 2020-02-03 15:56
@rerrahkr, in relation to your Twitter post (I'm unable to respond)
>ym2608のADPCMについて調べてたら、音源ボードによってはADPCMじゃなくてPCMを使ってる物も存在するのに気が付いて、実装が少し複雑になりそう 
When examining ym2608's ADPCM, I noticed that some sound source boards use PCM instead of ADPCM, so the implementation seems to be a little complicated  

NEC-PC9801-86 board is such - even while it contains YM2608B, which normally has ADPCM, it can't be used, since board lacks buffer RAM essential for sample data playback. Instead, one has to use onboard PCM (16-bit, 44kHz stereo codec). It is well emulated and even supported by PMD as PPZ8 - driver utilizing software mixing to output 8 PCM channels.
In the futher future, when ADPCM will be fully supported, it can be the next thing to implement to allow sample playback.

**Comment by rerrahkr** [comment] 2020-02-04 12:09
Thanks for your information, so it seems that PPZ8 can be reproduced simply by adding .wav samples to the current emulation sound.

**Comment by papiezak** [comment] 2020-02-04 13:01
Probably yes. There are anyway existing PCM formats used by PMD like .OZI, .P86, .PZI, .PVI..... they could also be reused for this, if only specs for them exist.
Also - emulation  inferface for PC-9801-86 PCM sound: https://github.com/AZO234/NP2kai/blob/master/sound/pcm86c.c

**Comment by OPNA2608** [comment] 2020-02-04 16:38
> There are anyway existing PCM formats used by PMD like .OZI, **.P86**, .PZI, .PVI..... they could also be reused for this, if only specs for them exist (they likely do).

If there are formal documentations for any of the PMD (sequence & bank) formats, I'm blind and unable to find them. I started to write some on my own in my free time though, maybe this helps you.

[.P86](https://github.com/OPNA2608/libopenpmd/blob/master/docs/p86.txt)

**Comment by papiezak** [comment] 2020-02-05 11:32
>If there are formal documentations for any of the PMD (sequence & bank) formats, I'm blind and unable to find them. 

KAJA, original creator of PMD, hosts a dozen of PMD-related utilities on his site [http://www5.airnet.ne.jp/kajapon/tool.html](url)
`Ver.4.8o - Freeware版` contains several .docs, however most of it seems to be general info, rather than full specs. Only noteworthy thing might be file header information for .PPS (SSGPCM), .PPC (ADPCM) and .P86: https://gist.github.com/papiezak/1841d4b010eed91263bdb19fa42a9d9f

**Comment by rerrahkr** [comment] 2020-02-25 13:07
I added ADPCM feature until 70c6625b15228e2904ee23b01fbde727af3cc0fa. Drumkit and waveform edit will be added in the future.

**Comment by rerrahkr** [comment] 2020-03-28 15:14
After the implementation of ADPCM instrument, I will work on ADPCM drum kit.

I plan ADPCM drum kit editor:

- It has key assign list and waveform editor.
- There are no envelope, arpeggio and pitch editor, specializing in only playing samples.
- Key assign list controls sample (waveform number) to play at note-on and its *pitch* (by seminote).
- Each sample can be edited waveform editor in the same way as that of ADPCM instrument editor.
- Waveform properties are shared with ADPCM instruments.

image by MS paint
![drunkit_sketch](https://user-images.githubusercontent.com/26477882/77825642-eb296300-714d-11ea-95c0-863bce2affc9.png)

It is also necessary to think how to add a drum kit to the instrument list. For example,  New Instrument icon has a drop-down menu and can be selected whether adding an ordinary instrument (default) or an drum kit.

**Comment by ImATrackMan** [comment] 2020-03-29 02:53
Adding an arpeggio macro might be useful in drumkit mode. You might want to play a sample one or two ticks after another or drum flams. Since Bamboo doesn't allow Gxx to be equal to the speed setting, there is no way to do that without making the speed very fast or playing a sample one tick early. If you do either, you can't do it more that once because the notes pile up.

**Comment by rerrahkr** [comment] 2020-03-29 13:32
An arpeggio macro editor affects the playback of all samples in the drumkit. How about switching samples by note transpose `0Txy`? Drumkit plays samples with a fixed pitch, and notes correspond to each sample, so you can change samples with pitch-related effects.

**Comment by rerrahkr** [comment] 2020-05-02 03:28
At f9230ce21691c372d307340505d68fd38bf72c74, I added drumkit and its editor.

**Comment by freq-mod** [comment] 2020-05-09 14:03
Regarding the ADPCM waveform edit feature you plan for future, what will it be like?
Will it only contain bare bones features like sample fragment deletion and tilt like in 0CC-Famitracker or more advanced options?

**Comment by rerrahkr** [comment] 2020-05-10 07:58
I planned to implement mouse edit, grid view, zoom in/out, etc.

**Comment by OPNA2608** [comment] 2020-10-30 10:44
> Now the basic ADPCM feature is implemented in BambooTracker.

Can this issue be closed & any new and leftover requests/bugs be tracked via new issues?

**Comment by rerrahkr** [comment] 2020-11-06 15:01
All 4 requests in the first post of this issue have been implemented. Regarding ADPCM, I'm dealing with improvements in new issues. So I close this issue.

In this issue, there were some discussion about SSG-PCM and 86 board PCM. It is unlikely that we will implement them at this time, but we were able to share some interesting information. Thank you everyone.

**Closed by rerrahkr** 2020-11-06 15:01 UTC
Labels: enhancement

**Comment by denjhang** [comment] 2021-11-26 02:51
At present, hardware VGM players such as MegaGRRL can play back SSGPCM correctly, why not consider supporting SSGPCM?

**Comment by freq-mod** [comment] 2021-11-26 07:54
Number of reasons (personally would love to have SSGPCM):
1. VGM format is greatly unoptimal for tasks like PSG PCM - resulting tracks are huge, and a pain to log/play back...
2. ...on anything that's not as modern as MegaGRRL. There are 8-bit computers with OPNA, they really struggle with SSGPCM to put it lightly. Even PC-98 would require a really fast CPU I believe.
3. It won't be very trivial to implement, similiarly to #188 

Better idea would be to make a driver that would play .btm files on real hardware. Then yeah, everything would be possible to implement. VGM is not the solution
