### ISSUE TITLE
Corrupt Module

### ISSUE THREAD

**Issue by Ravancloak** [rerrahkr/BambooTracker#170] opened 2019-12-13 21:57 UTC
Module is corrupt according to all versions of 0.3.2 (and 0.3.1, I think, OPNA2608 checked). Opens fine when I use the 0.3.0 winXP in wine, I don't have any other versions from 0.3.0 to test it on. I tried exporting the instruments as a bank, but that the bank can't be opened by 0.3.2, leading me to suspect that an instrument may be the cause. Module and bank attached. I haven't encountered any other modules that show as corrupt. I thought it FM ext mode, but another module that used that opened fine.
[snow_angels.zip](https://github.com/rerrahkr/BambooTracker/files/3962841/snow_angels.zip)

**Comment by ImATrackMan** [comment] 2019-12-14 00:05
All modules fail to open between 0.3.1 and 0.3.1/0.3.2

**Comment by Ravancloak** [comment] 2019-12-14 04:42
Strange, I only had that issue with this one module

**Comment by rerrahkr** [comment] 2019-12-14 12:20
Thanks for reports. There are two different bugs in the module and the bank.

The module is corrupted because the incorrect value of sequence type is set at FM pitch 3. I think this bug is due to the ambiguous definition of internal values for sequence type before v0.3.1. In latest version, this bug could have been fixed by the type value check before saving to the file.
I attached the fixed module here.
[Snow Angels FIXED.zip](https://github.com/rerrahkr/BambooTracker/files/3963776/Snow.Angels.FIXED.zip)

The bank corruption is caused by wrong instrument indexing in the bank export. I will fix it and release a new version.

**Comment by rerrahkr** [comment] 2019-12-14 16:37
I fixed the bank export at 5d90de220664de4aeda20c200f5898e709668d8d, this commit  prevents exporting corrupted file.

**Comment by ImATrackMan** [comment] 2019-12-14 21:45
If the problem was in the module saving process of 0.3.0 does that mean modules created in 0.3.0 and older are incompatible with 0.3.1/2?

**Comment by Ravancloak** [comment] 2019-12-15 00:08
evidence indicates otherwise - all my nodules work fine, aside from this one.

**Comment by galap-1** [comment] 2019-12-15 03:45
I don't know whether this is one of the known bugs or not, but I am having this problem with this module as well. 
[metalj.zip](https://github.com/rerrahkr/BambooTracker/files/3964575/metalj.zip)

**Comment by rerrahkr** [comment] 2019-12-15 08:56
I found that the sequence type of FM/SSG arpeggio and FM/SSG pitch were not copied in the instrument deep copy, which means the value of sequence type was not initialized and an unexpected value was written to files.

I fixed it at 7b151b601a1209afe1d38fe76c0b16330f9e4024 and I will revise version of module, instrument and bank to check the sequence type value in old files: If an incorrect sequence type is detected during file load, it will be modified to Absolute (0x00) automatically.
All unexpected sequence types will be replaced with Absolute, so you may need to modify appropriate sequence types after loading old files.

These changes will be posted to my Twitter and IMPORTANT.md. I'm sorry for the inconvenience.

**Comment by rerrahkr** [comment] 2019-12-16 15:05
> If an incorrect sequence type is detected during file load, it will be modified to Absolute (0x00) automatically.

I added this at e9bc31777b784700cd518539502bf2edf95ec739.

**Closed** 2020-03-18 13:57 UTC
