### ISSUE TITLE
Crash When loading Module (2.0 Latest, Includes Dev Build)

### ISSUE THREAD

**Issue by N-SPC700** [rerrahkr/BambooTracker#126] opened 2019-05-12 16:26 UTC
I recently updated from 1.6 of BambooTracker to 2.0 latest. I got curious and opened the newest demo module by SuperJetSpade(SJS), and listened through it. Then, I went and opened my module to continue working on something I was doing from a prior version. Program crashed, and error windows made Alt+F4 unable to close it, unless I closed it through Task Manager. After replicating, I can give the steps required to break BambooTracker.

1. Load the Underwater Ruins module by SJS.
2. Go to pattern frame 0F, and play it (doesn't matter how long).
3. Attempt to load my module.
4. BambooTracker should give an error related to vectors.
Edit: The error is `vector::_M_range_check: __n (which is 13) >= this->size() (which is 5)`

The module I use, which happened to break BT:
[Sophia (Take 2).zip](https://github.com/rerrahkr/BambooTracker/files/3170313/Sophia.Take.2.zip)

**Comment by OPNA2608** [comment] 2019-05-13 09:55
Can be reproduced with the demo modules `breeze2608.btm` and any of the other two demos.

1) Pick 2 modules, one has to be at least 2 Order list entries longer than the other one
2) Load the longer module
3) Move to an index in the Order view that's bigger than or equal to the smaller module's last Order index + 2
4) Attempt to load the smaller module

Example:
1) `breeze2608.btm` (0x20) and `Lotus.btm` (0x17, shorter by 9)
2) Load `breeze2608.btm`
3) Go to any Order index between 0x19 and 0x20
4) Attempt to load `Lotus.btm`

Error:
![grafik](https://user-images.githubusercontent.com/23431373/57612450-25f5cd00-7575-11e9-993d-63375361a555.png)

I think this is a problem with updating/resetting the current position [inside the Order View], as the vertical scroll bar of the Order List also doesn't correctly update its position when loading another module.
![grafik](https://user-images.githubusercontent.com/23431373/57612224-b7b10a80-7574-11e9-8240-cbdc5c66a0c0.png)
Pressing the down arrow of the scroll bar here results in the Order index jumping down to where it was on the old module (13 here) + 1
![grafik](https://user-images.githubusercontent.com/23431373/57612286-da432380-7574-11e9-96ed-663e7fc6ff20.png)

It's likely that somewhere, the Order position is not being updated correctly resulting in it trying to point to an Order entry that is beyond the new module's list.
(Weirdly, if it's just off by 1 it loads fine and the view even jumps to the last order instead of the start? Something doesn't look right there either.)

**Comment by N-SPC700** [comment] 2019-05-13 12:41
In 2.0(.11?) dev, you can kill it by closing the errors. Oddly enough 2.0 release doesn't, which requires intervening by Task Manager.

**Comment by rerrahkr** [comment] 2019-05-13 15:01
Thanks for reports, @N-SPC700, @OPNA2608.
I missed position initialization in the order list when loading a new song, so I fixed it at f2c05a8940f13e23caeddf7955b493c1deab50f7.

> Oddly enough 2.0 release doesn't, which requires intervening by Task Manager.

it doesn't occur on my windows 10, that's strange...

**Comment by rerrahkr** [comment] 2019-09-07 08:19
Since I have already fixed a bug on loading module, I close this issue.

**Closed by rerrahkr** 2019-09-07 08:19 UTC
