### ISSUE TITLE
[macOS] Can't click MIDI device option

### ISSUE THREAD

**Issue by OPNA2608** [rerrahkr/BambooTracker#240] opened 2020-07-12 02:13 UTC
macOS 10.15, a user is unable to _click_ on any MIDI device option. It gives them an error sfx and doesn't do anything. They _can_ however use the arrow keys and enter to select their device of choice, which otherwise works as expected.

![grafik](https://user-images.githubusercontent.com/23431373/87237328-3ca3e800-c3f5-11ea-96eb-223ce33923fb.png)

**Comment by rerrahkr** [comment] 2020-07-12 11:14
Thanks for your report. I confirmed it on macOS Mojave. As far as I checked, it looks like there is no problem with the source. Since it's only a problem on mac, I think it's a bug in Qt.

**Comment by rerrahkr** [comment] 2020-07-16 09:51
I replaced QToolButton caused this problem with QComboBox in #238. After merging that PR I will close this.

**Comment by OPNA2608** [comment] 2020-07-16 10:02
You can put `closes #240` in the PR description of #238, then GitHub will automatically close this issue when the corresponding PR gets merged.

**Closed** 2020-10-04 13:51 UTC
